### ISSUE TITLE
HW07 Part 2 Terns

### ISSUE THREAD

**Issue by williamzoughaib** [SEMO-GABD/public_discussion#12]
###Assignment 2: **Roseate Terns**
```{r}
library("tidyverse")
```
```{r}
?read_tsv
```
```{r}
terns_data <- read_tsv(here("data","roseate_terns.txt"))
# using read_tsv instead of read_csv
```
```{r}
terns_data
```

####Tidy the data
```{r}
tidy_terns <- as_tibble(terns_data)
# same exact thing as previous code chunk
```
```{r}
tidy_terns
```

####Filter out missing Counts
```{r}
?filter
```
```{r}
terns_filtered <- filter(drop_na(tidy_terns))
```
```{r}
terns_filtered
```

This is what I have done so far.  But when I try and create a line graph, I run into issues.  Are the site columns supposed to exist?  If so, do we then run a plot for each column?  Thats the simplest method I can think of but it would appear to be time consuming.  Is there another way?

**Comment by mtaylor-semo** [comment]
No, the site column does not exist.  You create the site column when you tidy the data. Using `as.tibble` does not make the data tidy. `as.tibble` takes a non-tibble data frame and makes it a tibble. Here, it is redundant because `read_csv` imports the data as a tibble. You're converting a tibble to a tibble.

Take a look at `pivot_longer` to make the data tidy.

**Comment by williamzoughaib** [comment]
I think I got it.  I used pivot_longer before but i forgot the key step of using %>% in there.
