### ISSUE TITLE
I have no idea what I am doing wrong.

### ISSUE THREAD

**Issue by CodyBohnert** [SEMO-GABD/public_discussion#3]
I keep trying to use the group_by() and summarise() to summarize the mean, depth, and velocity for each species in each riffle and I keep getting errors n matter what I try. Here is the code:
```{r}
by_species <- group_by(dartersb, species)
  darters_mean <- summarise(by_species,
                            length = mean(length, na.rm = TRUE),
                            depth(cm) = mean(depth(cm), na.rm = TRUE),
                            velocity = mean(velocity, na.rm = TRUE)
  )
```
The error is Error: unexpected '=' in:
"                            length = mean(length, na.rm = TRUE),
                            depth(cm) ="
I have tried removing the "=", but it then gives me an error saying depth object cannot be found. I have tried using depth(cm) and depth(mm). Any ideas?

**Comment by mtaylor-semo** [comment]
I believe the problem is that you have non-syntatic column names. "A syntactically valid name consists of letters, numbers and the dot or underline characters and starts with a letter or the dot not followed by a number. " (enter `?make.names` in your console).

In this case, you have a column called `depth(cm)`. Parentheses should not be used in column names. You can use your existing code with non-syntactic names by enclosing them in backticks, like this.

\`depth(cm)\` = mean(\`depth(cm)\`, na.rm = TRUE)

I do not recommend this as it is more typing and easy to miss a backtick and so hard to debug. 

The **best option** is to edit the earlier part of your code where you first use `depth(cm)` and change it to `depth_cm`. You still have a reminder of the unit of measure, but you also have a syntactically valid name.
