### ISSUE TITLE
Skip plot 5: I screwed up

### ISSUE THREAD

**Issue by mtaylor-semo** [SEMO-GABD/public_discussion#30]
All,

William (and Afreen by email) is correct. I screwed up my code for Plot 5. I found the county in each state that had the maximum number of cases, which was not my intent.  It's way too late to try to correct the exercise and expect you adjust.

I apologize for causing so much confusion. I screwed up.  You can skip plot 5. Or, make a choropleth that displays the data you want to display.

Mike

**Comment by afreenalam** [comment]
Dear Dr. Taylor
Is that also the case with plot 3?
Since the values are cumulative, to find new cases in April vs july, I subtracted number of (cumulative) cases from the end of month from the number of cases at the beginning of month. I got a table with State,  new cases (the diff), and population of state (using left_join) for the two months (102 rows).
My graph appears similar but not exactly the same as on in assignment. The values are larger by ~ 100, and the order of states is slightly off (the assignment said it should be in order of increasing cases but the graph did not appear similar so I put it in order of decreasing case rate of july).
What am I doing wrong?

[cid:ea8cb000-da08-4d19-bb58-d0d16804390e]





Regards
Afreen Alam

________________________________

**Comment by mtaylor-semo** [comment]
No, that's not the case with plot 3.

--
Michael S. Taylor
Professor of Biology
Dept. of Biology
Southeast Missouri State University
Cape Girardeau, MO 63701
(573) 651-2357
http://cstl.semo.edu/~mtaylor/
RH 217

On Aug 7, 2020, at 3:56 PM, afreenalam <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Dr. Taylor
Is that also the case with plot 3?
Since the values are cumulative, to find new cases in April vs july, I subtracted number of (cumulative) cases from the end of month from the number of cases at the beginning of month. I got a table with State, new cases (the diff), and population of state (using left_join) for the two months (102 rows).
My graph appears similar but not exactly the same as on in assignment. The values are larger by ~ 100, and the order of states is slightly off (the assignment said it should be in order of increasing cases but the graph did not appear similar so I put it in order of decreasing case rate of july).
What am I doing wrong?

[cid:ea8cb000-da08-4d19-bb58-d0d16804390e]





Regards
Afreen Alam

________________________________

**Comment by mtaylor-semo** [comment]
For Plot 3, I did have data in only through 24 July but that is now fixed. I found this easiest to start with a fresh import. You do need to subtract 1 April from 30 April to get the correct number of April cases. Same for July.

**Comment by afreenalam** [comment]
Thank you!
